CREATE DATABASE IF NOT EXISTS biblioteca;

USE biblioteca;

DROP USER 'biblioteca_user'@'%';

FLUSH PRIVILEGES;

CREATE USER 'biblioteca_user'@'%' IDENTIFIED WITH mysql_native_password BY 'biblioteca_user_password';

GRANT SELECT ON biblioteca.* TO 'biblioteca_user'@'%';

FLUSH PRIVILEGES;

CREATE TABLE AUTHOR (
  ID             int(10) NOT NULL AUTO_INCREMENT, 
  NAME           varchar(255) NOT NULL, 
  FIRST_SURNAME  varchar(255) NOT NULL, 
  SECOND_SURNAME varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE CAT_DOCUMENT_TYPE (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  NAME varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE CAT_FORMAT (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  NAME varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE CAT_GENRE (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  NAME varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE DELIVERY_TIME (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  TIME int(10) NOT NULL, 
  UNIT varchar(255), 
  PRIMARY KEY (ID));
CREATE TABLE DOCUMENT (
  ID               int(10) NOT NULL AUTO_INCREMENT, 
  TITLE            varchar(255) NOT NULL, 
  PRICE            real NOT NULL, 
  PAGE_NUMBER      int(10) NOT NULL, 
  AUTHOR_ID        int(10) NOT NULL, 
  GENRE_ID         int(10) NOT NULL, 
  DELIVERY_TIME_ID int(10) NOT NULL, 
  EDITORIAL_ID     int(10) NOT NULL, 
  FORMAT_ID        int(10) NOT NULL, 
  DOCUMENT_TYPE_ID int(10) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE EDITORIAL (
  ID   int(10) NOT NULL AUTO_INCREMENT, 
  NAME varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
CREATE TABLE USERS (
  ID       int(10) NOT NULL AUTO_INCREMENT, 
  USERNAME varchar(255) NOT NULL, 
  PASSWORD varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
ALTER TABLE DOCUMENT ADD CONSTRAINT DELIVERED_ON FOREIGN KEY (DELIVERY_TIME_ID) REFERENCES DELIVERY_TIME (ID);
ALTER TABLE DOCUMENT ADD CONSTRAINT IS_OF_GENRE FOREIGN KEY (GENRE_ID) REFERENCES CAT_GENRE (ID);
ALTER TABLE DOCUMENT ADD CONSTRAINT IS_OF_TYPE FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES CAT_DOCUMENT_TYPE (ID);
ALTER TABLE DOCUMENT ADD CONSTRAINT IS_ON_FORMAT FOREIGN KEY (FORMAT_ID) REFERENCES CAT_FORMAT (ID);
ALTER TABLE DOCUMENT ADD CONSTRAINT PUBLISHED_BY FOREIGN KEY (EDITORIAL_ID) REFERENCES EDITORIAL (ID);
ALTER TABLE DOCUMENT ADD CONSTRAINT WRITED_BY FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID);

INSERT INTO USERS(USERNAME, PASSWORD) VALUES
('admin', '686d4ba6996ab7e2bd626c9a3cc965c6'); -- admin , biblioteca

INSERT INTO CAT_FORMAT(NAME) VALUES
('Impreso'),
('Electrónico');

INSERT INTO CAT_DOCUMENT_TYPE(NAME) VALUES
('Libros'),
('Periódico'),
('Revista');
